{
 "title": "Boilerhouse",
 "tags": [ "boilerhouse" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "pool_id",
    "label": "Pool",
    "query": "label_values(boilerhouse_pool_size, pool_id)"
   },
   {
    "name": "workload_id",
    "label": "Workload",
    "query": "label_values(boilerhouse_pool_size, workload_id)"
   }
  ]
 },
 "panels": [
  { "title": "Pools", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pool Status",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "boilerhouse_pool_size{pool_id=~\"$pool_id\"}"
    },
    {
     "expr": "boilerhouse_pool_min_size{pool_id=~\"$pool_id\"}"
    },
    {
     "expr": "boilerhouse_pool_max_size{pool_id=~\"$pool_id\"}"
    },
    {
     "expr": "boilerhouse_pool_borrowed{pool_id=~\"$pool_id\"}"
    },
    {
     "expr": "boilerhouse_pool_available{pool_id=~\"$pool_id\"}"
    },
    {
     "expr": "boilerhouse_pool_borrowed{pool_id=~\"$pool_id\"} / boilerhouse_pool_size{pool_id=~\"$pool_id\"} * 100"
    },
    {
     "expr": "rate(boilerhouse_affinity_hits_total{pool_id=~\"$pool_id\"}[$__rate_interval]) / (rate(boilerhouse_affinity_hits_total{pool_id=~\"$pool_id\"}[$__rate_interval]) + rate(boilerhouse_affinity_misses_total{pool_id=~\"$pool_id\"}[$__rate_interval])) * 100"
    }
   ]
  },
  { "title": "Containers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Containers",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "boilerhouse_container_info{pool_id=~\"$pool_id\"}"
    }
   ]
  },
  { "title": "Syncs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Sync Operations",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sum by (workload_id) (increase(boilerhouse_sync_operations_total{workload_id=~\"$workload_id\", direction=\"upload\"}[$__range]))"
    },
    {
     "expr": "sum by (workload_id) (increase(boilerhouse_sync_operations_total{workload_id=~\"$workload_id\", direction=\"download\"}[$__range]))"
    },
    {
     "expr": "sum by (workload_id) (increase(boilerhouse_sync_operations_total{workload_id=~\"$workload_id\", direction=\"bidirectional\"}[$__range]))"
    },
    {
     "expr": "histogram_quantile(0.5, sum by (workload_id, le) (rate(boilerhouse_sync_duration_seconds_bucket{workload_id=~\"$workload_id\"}[$__rate_interval])))"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (workload_id, le) (rate(boilerhouse_sync_duration_seconds_bucket{workload_id=~\"$workload_id\"}[$__rate_interval])))"
    },
    {
     "expr": "sum by (workload_id) (increase(boilerhouse_sync_bytes_transferred_total{workload_id=~\"$workload_id\"}[$__range]))"
    },
    {
     "expr": "sum by (workload_id) (increase(boilerhouse_sync_files_transferred_total{workload_id=~\"$workload_id\"}[$__range]))"
    },
    {
     "expr": "boilerhouse_sync_concurrent_operations{workload_id=~\"$workload_id\"}"
    },
    {
     "expr": "boilerhouse_sync_queue_length{workload_id=~\"$workload_id\"}"
    },
    {
     "expr": "sum by (workload_id) (increase(boilerhouse_sync_errors_total{workload_id=~\"$workload_id\"}[$__range]))"
    },
    {
     "expr": "sum by (workload_id) (increase(boilerhouse_sync_bisync_resync_total{workload_id=~\"$workload_id\"}[$__range]))"
    }
   ]
  }
 ]
}