apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - boilerhouse.dev_boilerhouseworkloads.yaml
  - boilerhouse.dev_boilerhousepools.yaml
  - boilerhouse.dev_boilerhouseclaims.yaml
  - boilerhouse.dev_boilerhousetriggers.yaml
