//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BoilerhouseClaim) DeepCopyInto(out *BoilerhouseClaim) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BoilerhouseClaim.
func (in *BoilerhouseClaim) DeepCopy() *BoilerhouseClaim {
	if in == nil {
		return nil
	}
	out := new(BoilerhouseClaim)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BoilerhouseClaim) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BoilerhouseClaimList) DeepCopyInto(out *BoilerhouseClaimList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BoilerhouseClaim, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BoilerhouseClaimList.
func (in *BoilerhouseClaimList) DeepCopy() *BoilerhouseClaimList {
	if in == nil {
		return nil
	}
	out := new(BoilerhouseClaimList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BoilerhouseClaimList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BoilerhouseClaimSpec) DeepCopyInto(out *BoilerhouseClaimSpec) {
	*out = *in
	if in.Resume != nil {
		in, out := &in.Resume, &out.Resume
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BoilerhouseClaimSpec.
func (in *BoilerhouseClaimSpec) DeepCopy() *BoilerhouseClaimSpec {
	if in == nil {
		return nil
	}
	out := new(BoilerhouseClaimSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BoilerhouseClaimStatus) DeepCopyInto(out *BoilerhouseClaimStatus) {
	*out = *in
	if in.Endpoint != nil {
		in, out := &in.Endpoint, &out.Endpoint
		*out = new(ClaimEndpoint)
		**out = **in
	}
	if in.ClaimedAt != nil {
		in, out := &in.ClaimedAt, &out.ClaimedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BoilerhouseClaimStatus.
func (in *BoilerhouseClaimStatus) DeepCopy() *BoilerhouseClaimStatus {
	if in == nil {
		return nil
	}
	out := new(BoilerhouseClaimStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BoilerhousePool) DeepCopyInto(out *BoilerhousePool) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BoilerhousePool.
func (in *BoilerhousePool) DeepCopy() *BoilerhousePool {
	if in == nil {
		return nil
	}
	out := new(BoilerhousePool)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BoilerhousePool) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BoilerhousePoolList) DeepCopyInto(out *BoilerhousePoolList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BoilerhousePool, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BoilerhousePoolList.
func (in *BoilerhousePoolList) DeepCopy() *BoilerhousePoolList {
	if in == nil {
		return nil
	}
	out := new(BoilerhousePoolList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BoilerhousePoolList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BoilerhousePoolSpec) DeepCopyInto(out *BoilerhousePoolSpec) {
	*out = *in
	if in.MaxFillConcurrency != nil {
		in, out := &in.MaxFillConcurrency, &out.MaxFillConcurrency
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BoilerhousePoolSpec.
func (in *BoilerhousePoolSpec) DeepCopy() *BoilerhousePoolSpec {
	if in == nil {
		return nil
	}
	out := new(BoilerhousePoolSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BoilerhousePoolStatus) DeepCopyInto(out *BoilerhousePoolStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BoilerhousePoolStatus.
func (in *BoilerhousePoolStatus) DeepCopy() *BoilerhousePoolStatus {
	if in == nil {
		return nil
	}
	out := new(BoilerhousePoolStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BoilerhouseTrigger) DeepCopyInto(out *BoilerhouseTrigger) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BoilerhouseTrigger.
func (in *BoilerhouseTrigger) DeepCopy() *BoilerhouseTrigger {
	if in == nil {
		return nil
	}
	out := new(BoilerhouseTrigger)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BoilerhouseTrigger) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BoilerhouseTriggerList) DeepCopyInto(out *BoilerhouseTriggerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BoilerhouseTrigger, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BoilerhouseTriggerList.
func (in *BoilerhouseTriggerList) DeepCopy() *BoilerhouseTriggerList {
	if in == nil {
		return nil
	}
	out := new(BoilerhouseTriggerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BoilerhouseTriggerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BoilerhouseTriggerSpec) DeepCopyInto(out *BoilerhouseTriggerSpec) {
	*out = *in
	if in.Tenant != nil {
		in, out := &in.Tenant, &out.Tenant
		*out = new(TriggerTenant)
		**out = **in
	}
	if in.DriverOptions != nil {
		in, out := &in.DriverOptions, &out.DriverOptions
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
	if in.Guards != nil {
		in, out := &in.Guards, &out.Guards
		*out = make([]TriggerGuard, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BoilerhouseTriggerSpec.
func (in *BoilerhouseTriggerSpec) DeepCopy() *BoilerhouseTriggerSpec {
	if in == nil {
		return nil
	}
	out := new(BoilerhouseTriggerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BoilerhouseTriggerStatus) DeepCopyInto(out *BoilerhouseTriggerStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BoilerhouseTriggerStatus.
func (in *BoilerhouseTriggerStatus) DeepCopy() *BoilerhouseTriggerStatus {
	if in == nil {
		return nil
	}
	out := new(BoilerhouseTriggerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BoilerhouseWorkload) DeepCopyInto(out *BoilerhouseWorkload) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BoilerhouseWorkload.
func (in *BoilerhouseWorkload) DeepCopy() *BoilerhouseWorkload {
	if in == nil {
		return nil
	}
	out := new(BoilerhouseWorkload)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BoilerhouseWorkload) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BoilerhouseWorkloadList) DeepCopyInto(out *BoilerhouseWorkloadList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BoilerhouseWorkload, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BoilerhouseWorkloadList.
func (in *BoilerhouseWorkloadList) DeepCopy() *BoilerhouseWorkloadList {
	if in == nil {
		return nil
	}
	out := new(BoilerhouseWorkloadList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BoilerhouseWorkloadList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BoilerhouseWorkloadSpec) DeepCopyInto(out *BoilerhouseWorkloadSpec) {
	*out = *in
	out.Image = in.Image
	out.Resources = in.Resources
	if in.Network != nil {
		in, out := &in.Network, &out.Network
		*out = new(WorkloadNetwork)
		(*in).DeepCopyInto(*out)
	}
	if in.Filesystem != nil {
		in, out := &in.Filesystem, &out.Filesystem
		*out = new(WorkloadFilesystem)
		(*in).DeepCopyInto(*out)
	}
	if in.Idle != nil {
		in, out := &in.Idle, &out.Idle
		*out = new(WorkloadIdle)
		(*in).DeepCopyInto(*out)
	}
	if in.Health != nil {
		in, out := &in.Health, &out.Health
		*out = new(WorkloadHealth)
		(*in).DeepCopyInto(*out)
	}
	if in.Entrypoint != nil {
		in, out := &in.Entrypoint, &out.Entrypoint
		*out = new(WorkloadEntrypoint)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BoilerhouseWorkloadSpec.
func (in *BoilerhouseWorkloadSpec) DeepCopy() *BoilerhouseWorkloadSpec {
	if in == nil {
		return nil
	}
	out := new(BoilerhouseWorkloadSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BoilerhouseWorkloadStatus) DeepCopyInto(out *BoilerhouseWorkloadStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BoilerhouseWorkloadStatus.
func (in *BoilerhouseWorkloadStatus) DeepCopy() *BoilerhouseWorkloadStatus {
	if in == nil {
		return nil
	}
	out := new(BoilerhouseWorkloadStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClaimEndpoint) DeepCopyInto(out *ClaimEndpoint) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClaimEndpoint.
func (in *ClaimEndpoint) DeepCopy() *ClaimEndpoint {
	if in == nil {
		return nil
	}
	out := new(ClaimEndpoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HealthExec) DeepCopyInto(out *HealthExec) {
	*out = *in
	if in.Command != nil {
		in, out := &in.Command, &out.Command
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HealthExec.
func (in *HealthExec) DeepCopy() *HealthExec {
	if in == nil {
		return nil
	}
	out := new(HealthExec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HealthHTTPGet) DeepCopyInto(out *HealthHTTPGet) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HealthHTTPGet.
func (in *HealthHTTPGet) DeepCopy() *HealthHTTPGet {
	if in == nil {
		return nil
	}
	out := new(HealthHTTPGet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkCredential) DeepCopyInto(out *NetworkCredential) {
	*out = *in
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(SecretKeyRef)
		**out = **in
	}
	if in.Headers != nil {
		in, out := &in.Headers, &out.Headers
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkCredential.
func (in *NetworkCredential) DeepCopy() *NetworkCredential {
	if in == nil {
		return nil
	}
	out := new(NetworkCredential)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkExposePort) DeepCopyInto(out *NetworkExposePort) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkExposePort.
func (in *NetworkExposePort) DeepCopy() *NetworkExposePort {
	if in == nil {
		return nil
	}
	out := new(NetworkExposePort)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretKeyRef) DeepCopyInto(out *SecretKeyRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretKeyRef.
func (in *SecretKeyRef) DeepCopy() *SecretKeyRef {
	if in == nil {
		return nil
	}
	out := new(SecretKeyRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TriggerGuard) DeepCopyInto(out *TriggerGuard) {
	*out = *in
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TriggerGuard.
func (in *TriggerGuard) DeepCopy() *TriggerGuard {
	if in == nil {
		return nil
	}
	out := new(TriggerGuard)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TriggerTenant) DeepCopyInto(out *TriggerTenant) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TriggerTenant.
func (in *TriggerTenant) DeepCopy() *TriggerTenant {
	if in == nil {
		return nil
	}
	out := new(TriggerTenant)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadEntrypoint) DeepCopyInto(out *WorkloadEntrypoint) {
	*out = *in
	if in.Args != nil {
		in, out := &in.Args, &out.Args
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadEntrypoint.
func (in *WorkloadEntrypoint) DeepCopy() *WorkloadEntrypoint {
	if in == nil {
		return nil
	}
	out := new(WorkloadEntrypoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadFilesystem) DeepCopyInto(out *WorkloadFilesystem) {
	*out = *in
	if in.OverlayDirs != nil {
		in, out := &in.OverlayDirs, &out.OverlayDirs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.EncryptOverlays != nil {
		in, out := &in.EncryptOverlays, &out.EncryptOverlays
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadFilesystem.
func (in *WorkloadFilesystem) DeepCopy() *WorkloadFilesystem {
	if in == nil {
		return nil
	}
	out := new(WorkloadFilesystem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadHealth) DeepCopyInto(out *WorkloadHealth) {
	*out = *in
	if in.HTTPGet != nil {
		in, out := &in.HTTPGet, &out.HTTPGet
		*out = new(HealthHTTPGet)
		**out = **in
	}
	if in.Exec != nil {
		in, out := &in.Exec, &out.Exec
		*out = new(HealthExec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadHealth.
func (in *WorkloadHealth) DeepCopy() *WorkloadHealth {
	if in == nil {
		return nil
	}
	out := new(WorkloadHealth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadIdle) DeepCopyInto(out *WorkloadIdle) {
	*out = *in
	if in.WatchDirs != nil {
		in, out := &in.WatchDirs, &out.WatchDirs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadIdle.
func (in *WorkloadIdle) DeepCopy() *WorkloadIdle {
	if in == nil {
		return nil
	}
	out := new(WorkloadIdle)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadImage) DeepCopyInto(out *WorkloadImage) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadImage.
func (in *WorkloadImage) DeepCopy() *WorkloadImage {
	if in == nil {
		return nil
	}
	out := new(WorkloadImage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadNetwork) DeepCopyInto(out *WorkloadNetwork) {
	*out = *in
	if in.Expose != nil {
		in, out := &in.Expose, &out.Expose
		*out = make([]NetworkExposePort, len(*in))
		copy(*out, *in)
	}
	if in.Allowlist != nil {
		in, out := &in.Allowlist, &out.Allowlist
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Credentials != nil {
		in, out := &in.Credentials, &out.Credentials
		*out = make([]NetworkCredential, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadNetwork.
func (in *WorkloadNetwork) DeepCopy() *WorkloadNetwork {
	if in == nil {
		return nil
	}
	out := new(WorkloadNetwork)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadResources) DeepCopyInto(out *WorkloadResources) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadResources.
func (in *WorkloadResources) DeepCopy() *WorkloadResources {
	if in == nil {
		return nil
	}
	out := new(WorkloadResources)
	in.DeepCopyInto(out)
	return out
}
